# Generated by Django 5.0.3 on 2024-04-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_visitor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visitor",
            new_name="ViewerCount",
        ),
    ]
