# Generated by Django 5.0.3 on 2024-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="height",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="width",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
