# Generated by Django 5.0.3 on 2024-04-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_size_height_alter_size_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photoframe",
            name="Frame_size",
        ),
        migrations.RemoveField(
            model_name="photoframe",
            name="color",
        ),
    ]
