# Generated by Django 5.0.3 on 2024-04-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_photoframe_frame_size_remove_photoframe_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photoframe",
            name="discount",
        ),
    ]
