# Generated by Django 5.0.3 on 2024-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_phototour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoframe",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
