# Generated by Django 5.0.3 on 2024-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_photoframe_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("ip_address", models.CharField(max_length=50, null=True)),
                ("session_id", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ViewerCount",
        ),
    ]
